"""policies table creation

Revision ID: 7a715cc13b00
Revises: 
Create Date: 2025-12-21 13:40:15.407685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a715cc13b00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'action', name='_category_action_unq'),
    sa.UniqueConstraint('policy_name')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
